CREATE TABLE IF NOT EXISTS public.testdrive_request
(
  testdrive_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_id          integer NOT NULL,
  account_id      integer NOT NULL,
  preferred_date  date NOT NULL,
  preferred_time  varchar(10) NOT NULL,
  contact_phone   varchar(20) NOT NULL,
  message         text,
  status          varchar(20) NOT NULL DEFAULT 'Pending',
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_testdrive_inventory
    FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_testdrive_account
    FOREIGN KEY (account_id)
    REFERENCES public.account (account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
